### ISSUE TITLE
Feature Request: different prefix list name for IPv4 and IPv6

### ISSUE THREAD

**Issue by esundberg** [6connect/irrpt#21]
Can you support having the IPv4 and IPv6 have different prefix names. We prepend all IPv4 Prefixes list names with IPV4 and for IPV6 Prefixes list we do the same.

Example
in the file conf/irrpt.conf
$cfg['pfxgen']['default_pfxstr_v4']        = "IPV4-AS%d-IN";
$cfg['pfxgen']['default_pfxstr_v6']        = "IPV6-AS%d-IN";

[user@server irrpt]$ bin/irrpt_pfxgen -f cisco 42
conf t
no ip prefix-list IPV4-AS42-IN
ip prefix-list IPV4-AS42-IN permit 216.21.2.0/23 le 24
no ip prefix-list IPV6-AS42-IN
ipv6 prefix-list IPV6-AS42-IN permit 2a01:8840:00a1:0000:0000:0000:0000:0000/48

Thanks!

**Comment by fooelisa** [comment]
Sure thing, just pushed the change to the master branch from #22 - check it out!

**Comment by esundberg** [comment]
Awesome thanks!!!
