### ISSUE TITLE
hardcoded items - :V6, php path

### ISSUE THREAD

**Issue by falz** [6connect/irrpt#34]
to work on more platforms, consider changing the shebang insted to be "/usr/bin/env php"

also, the v6 pfxlist generator hard codes ":V6" at the end which is inflexible and unnecssary as you can just repliate this in the config. inc/pfxlist.inc.

http://falz.net/static/irrpt-paths-v6.diff

**Comment by fooelisa** [comment]
Good points! Thanks! I merged the patch into the master branch.
