### ISSUE TITLE
Cisco IOSXR support

### ISSUE THREAD

**Issue by nistorj** [6connect/irrpt#44]
Attached patch for Cisco IOS XR prefix-sets.  This SHOULD be used with the -p6 flag on the CLI as the names by default are the same,  PEER:%d. 

[irrpt-XR.patch.txt](https://github.com/6connect/irrpt/files/174584/irrpt-XR.patch.txt)

**Comment by fooelisa** [comment]
added in 5bbb60b5e399ad26081f9f329ae29e472efdcad8
