### ISSUE TITLE
irrpt_fetch doesn't process AS-SET from irrdb.conf if AS# specified in CLI

### ISSUE THREAD

**Issue by nistorj** [6connect/irrpt#46]
Hi team,

Thinking the issue may be around the rewrite of the CLI parsing and parsing of irrdb.conf around here:
+// check AS parameter if provided 
+if (isset($_SERVER['argv'][$offset+0]))
+{
-  if (preg_match("/^AS./i", $_SERVER['argv'][$offset+0])) {
- ```
    $asString = strtoupper($_SERVER['argv'][$offset+0]);
  ```
- ```
    $rev = track($routefile);
  ```
  
  ..... etcetc

It seems that if you run ./irrpt_fetch -v <AS#> from the CLI it runs a fetch against just that AS number itself.  In version 1.27 it would check it against the irrdb.conf entry and if an AS-SET was specified it would use that AS-SET information instead of just the AS#.

Version 1.27:
nistor@base:/usr/local/irrpt.orig/bin# ./irrpt_fetch -v 30176
Processing AS30176 (Record 1)
   **\- Querying IRR Object AS30176:AS-CUSTOMERS**
- WARNING: IRR Query - key not found - Query: !gAS30176:AS-CUSTOMERS
- Writing ASN list to local database.
- Filtering against excluded routes.
- Writing routes to local database.
- Aggregating routes.
- Tracking data in CVS.

Version 2.0:
nistor@base:/usr/local/irrpt/bin# ./irrpt_fetch -v 30176
Processing AS30176 (Record 1)
   **\- Querying IRR Object AS30176**
- Fetching v4 routes.
- Filtering against excluded routes.
- Writing routes to local database.
- Aggregating v4 routes.
- Aggregating routes - sorting...
- Aggregating routes - eliminating overlapping prefixes...
- Aggregating routes - aggregating neighboring prefixes...
- Fetching v6 routes.
- Filtering against excluded routes.
- Writing routes to local database.
- Aggregating v6 routes.
  ......

please fix :)

**Comment by dominosly** [comment]
Hi Jon
Verified this tonight and figured out where the issue is. Will work on the fix tomorrow evening.

-Anna

**Comment by nistorj** [comment]
Hi Anna, any luck on getting this cleaned up?

**Comment by nistorj** [comment]
We have a working patch available, some more testing is taking place, if all works out a patch will be committed by end of the weekend.

**Comment by nistorj** [comment]
Resolved issue.
