### ISSUE TITLE
Route aggregation not working

### ISSUE THREAD

**Issue by devicenull** [6connect/irrpt#47]
Take AS15412  - AS-FLAGP as an example.  Their raw v4 prefix list has 572686 entries.  The aggregated one drops down to 75906, but still contains a bunch of entries that could be aggregated further.

For example, this is part of the 15412.4.agg file:

<pre>
2.99.146.0/24
2.99.147.0/24
2.99.148.0/24
2.99.149.0/24
2.99.150.0/24
2.99.151.0/24
2.99.152.0/24
2.99.153.0/24
2.99.154.0/24
2.99.155.0/24
2.99.156.0/24
2.99.157.0/24
2.99.158.0/24
2.99.159.0/24
2.99.160.0/24
2.99.161.0/24
2.99.162.0/24
2.99.163.0/24
2.99.164.0/24
2.99.165.0/24
2.99.166.0/24
2.99.167.0/24
2.99.168.0/24
2.99.169.0/24
2.99.170.0/24
2.99.171.0/24
2.99.172.0/24
2.99.173.0/24
2.99.174.0/24
</pre>

Shouldn't this be aggregated down a lot further?

**Comment by dominosly** [comment]
Fixed in PR #48 https://github.com/6connect/irrpt/pull/48
