### ISSUE TITLE
quiet mode missing final completed statement

### ISSUE THREAD

**Issue by nistorj** [6connect/irrpt#50]
Hi,

Looks like one small change required:

if( $o_quiet == 1 )
{
    status(STATUS_INFO, "Completed processing of {$count} IRR object(s).");
}

that should read o_quiet == 0

QA:
portal@base:~% /usr/local/irrpt/bin/irrpt_fetch -q --nocvs
portal@base:~%

works when the value is 0.

Cheers,
-nistor

**Comment by dominosly** [comment]
Updated - looks like it works as expected.

**Comment by nistorj** [comment]
Issue resolved.
